package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/sashabaranov/go-openai"
)

type GMBAIService struct {
	Client *openai.Client
}

func NewGMBAIService(apiKey string) *GMBAIService {
	if apiKey == "" {
		return &GMBAIService{Client: nil}
	}
	return &GMBAIService{Client: openai.NewClient(apiKey)}
}

// AIClassificationResult represents the structured output from AI
type AIClassificationResult struct {
	MainCategory string `json:"main_category"`
	SubCategory  string `json:"sub_category"`
	Brand        string `json:"brand"`
	Purpose      string `json:"purpose"`
}

// Suggestion represents a post idea generated by AI
type Suggestion struct {
	Category string `json:"category"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

// GenerateSuggestions generates post ideas based on missing categories
func (s *GMBAIService) GenerateSuggestions(missingCategories []string) ([]Suggestion, error) {
	if s.Client == nil {
		return s.heuristicSuggestions(missingCategories), nil
	}

	cats := strings.Join(missingCategories, ", ")
	prompt := fmt.Sprintf(`You are a local marketing expert for a Homeopathy Pharmacy in Gurgaon, India.

Generate 3 compelling Google My Business post ideas for these missing categories: %s.

FOCUS ON:
- Local Gurgaon audience (mention local landmarks, seasons, or events)
- Common health issues in NCR region
- Daily posting schedule to increase local visibility
- Building trust in local community
- Homeopathic solutions for seasonal ailments

Return JSON array:
[
  { 
    "category": "...", 
    "title": "Short catchy title (5-7 words)", 
    "content": "Engaging post content 150-200 characters mentioning Gurgaon/local area. Include call-to-action." 
  }
]

Make content actionable, professional, and focused on reaching local customers.`, cats)

	resp, err := s.Client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT3Dot5Turbo,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleSystem,
					Content: "You are a local social media marketing expert for a Homeopathy Pharmacy in Gurgaon, NCR. Focus on local audience engagement and community building. Return ONLY valid JSON.",
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
			},
		},
	)

	if err != nil {
		return s.heuristicSuggestions(missingCategories), err
	}

	var suggestions []Suggestion
	contentResp := resp.Choices[0].Message.Content
	contentResp = strings.TrimPrefix(contentResp, "```json")
	contentResp = strings.TrimSuffix(contentResp, "```")

	if err := json.Unmarshal([]byte(contentResp), &suggestions); err != nil {
		return s.heuristicSuggestions(missingCategories), nil
	}

	return suggestions, nil
}

// CategorizePost determines the category of a post content using advanced classification
func (s *GMBAIService) CategorizePost(content string) (*AIClassificationResult, error) {
	// Fallback if no API key
	if s.Client == nil {
		return s.heuristicCategorization(content), nil
	}

	prompt := `You are analyzing posts for a Homeopathy Retail Pharmacy.
Categorize the post using this system:

MAIN_CATEGORIES:
- Mother Tinctures
- Dilutions (Potencies)
- Biochemic Salts
- Trituration Tablets
- Ointments & Creams
- Syrups & Drops
- Kids Remedies
- Seasonal Medicines
- Cosmetic Homeopathy
- German/Imported Medicines
- Offers & Discounts
- New Stock Arrivals
- Clinic Updates
- Customer Reviews
- Educational/Tips
- Festival Greetings
- Events/Announcements

SUB_CATEGORIES examples:
- Acne, Hair Fall, Cough, Cold, Sinus, Immunity, Pain Relief
- 30C/200C/1M potencies
- Skin, Respiratory, Digestive, Hormonal, Women Care

BRAND examples:
SBL, Schwabe, Adel, Reckeweg, Willmar, Bakson.

Return JSON:
{
  "main_category": "",
  "sub_category": "",
  "brand": "",
  "purpose": ""
}

POST:
"` + content + `"`

	resp, err := s.Client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT3Dot5Turbo,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleSystem,
					Content: "You are an AI assistant for a Homeopathy Clinic. Return ONLY JSON.",
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
			},
		},
	)

	if err != nil {
		return &AIClassificationResult{MainCategory: "Other"}, err
	}

	var result AIClassificationResult
	contentResp := resp.Choices[0].Message.Content
	contentResp = strings.TrimPrefix(contentResp, "```json")
	contentResp = strings.TrimSuffix(contentResp, "```")

	if err := json.Unmarshal([]byte(contentResp), &result); err != nil {
		// Fallback if JSON parsing fails
		return &AIClassificationResult{MainCategory: "Other", Purpose: "Failed to parse AI response"}, nil
	}

	return &result, nil
}

func (s *GMBAIService) heuristicCategorization(content string) *AIClassificationResult {
	lower := strings.ToLower(content)
	result := &AIClassificationResult{MainCategory: "Other"}

	if strings.Contains(lower, "%") || strings.Contains(lower, "off") || strings.Contains(lower, "discount") {
		result.MainCategory = "Offers & Discounts"
		result.Purpose = "Sales"
	} else if strings.Contains(lower, "medicine") || strings.Contains(lower, "remedy") || strings.Contains(lower, "product") {
		result.MainCategory = "Dilutions (Potencies)"
		result.Purpose = "Product Info"
	} else if strings.Contains(lower, "tip") || strings.Contains(lower, "help") || strings.Contains(lower, "guide") {
		result.MainCategory = "Educational/Tips"
		result.Purpose = "Education"
	} else if strings.Contains(lower, "winter") || strings.Contains(lower, "summer") || strings.Contains(lower, "season") {
		result.MainCategory = "Seasonal Medicines"
		result.Purpose = "Seasonal"
	} else if strings.Contains(lower, "review") || strings.Contains(lower, "testimonial") {
		result.MainCategory = "Customer Reviews"
		result.Purpose = "Social Proof"
	} else if strings.Contains(lower, "open") || strings.Contains(lower, "closed") || strings.Contains(lower, "time") {
		result.MainCategory = "Clinic Updates"
		result.Purpose = "Info"
	}

	return result
}

func (s *GMBAIService) heuristicSuggestions(categories []string) []Suggestion {
	var suggestions []Suggestion
	for _, cat := range categories {
		suggestions = append(suggestions, Suggestion{
			Category: cat,
			Title:    fmt.Sprintf("New %s Post", cat),
			Content:  fmt.Sprintf("Draft content for %s...", cat),
		})
	}
	return suggestions
}
