-- ============================================================================
-- SAMPLE HOMEOPATHY PRODUCTS - Top 30 Essential Medicines
-- Production-ready starter inventory for homeopathy pharmacy
-- ============================================================================

-- Top 20 Dilutions (Most prescribed 30C potency)
INSERT INTO products (id, sku, name, category, brand, potency, form, pack_size, uom, cost_price, selling_price, mrp, tax_percent, hsn_code, manufacturer, description, barcode, reorder_level, min_stock, max_stock, current_stock, is_active, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'SBL-ARN-30C-30ML', 'Arnica Montana 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Trauma, injuries, bruising, muscle pain', '', 20, 10, 200, 50, true, 'trauma,injury,bruising,pain', now(), now()),
(gen_random_uuid(), 'SBL-BELL-30C-30ML', 'Belladonna 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Fever, inflammation, throbbing headache', '', 20, 10, 200, 50, true, 'fever,inflammation,headache', now(), now()),
(gen_random_uuid(), 'SBL-CALC-30C-30ML', 'Calcarea Carbonica 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Calcium disorders, bone development', '', 15, 10, 150, 40, true, 'calcium,bone,growth', now(), now()),
(gen_random_uuid(), 'SBL-NUX-30C-30ML', 'Nux Vomica 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Digestive upset, hangover, irritability', '', 20, 10, 200, 60, true, 'digestion,hangover,acidity', now(), now()),
(gen_random_uuid(), 'SBL-RHUS-30C-30ML', 'Rhus Toxicodendron 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Joint pain, stiffness, arthritis', '', 20, 10, 200, 50, true, 'joint,arthritis,pain', now(), now()),
(gen_random_uuid(), 'SBL-PULS-30C-30ML', 'Pulsatilla Nigricans 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Hormonal, emotional, weeping tendency', '', 15, 10, 150, 40, true, 'hormonal,emotional,pms', now(), now()),
(gen_random_uuid(), 'SBL-APIS-30C-30ML', 'Apis Mellifica 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Swelling, edema, allergic reactions', '', 15, 10, 150, 40, true, 'swelling,allergy,edema', now(), now()),
(gen_random_uuid(), 'SBL-PHOS-30C-30ML', 'Phosphorus 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Bleeding tendency, respiratory issues', '', 15, 10, 150, 40, true, 'bleeding,respiratory,cough', now(), now()),
(gen_random_uuid(), 'SBL-LYCO-30C-30ML', 'Lycopodium Clavatum 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Liver, digestive, flatulence', '', 15, 10, 150, 40, true, 'liver,digestion,gas', now(), now()),
(gen_random_uuid(), 'SBL-BRYK-30C-30ML', 'Bryonia Alba 30C', 'Dilutions', 'SBL (Dr. Willmar Schwabe)', '30C', 'Liquid (Dilution)', '30ml', 'ml', 75, 95, 110, 12, '30049011', 'SBL', 'Worse with motion, dry cough', '', 15, 10, 150, 40, true, 'cough,pain,fever', now(), now());

-- Top 5 Mother Tinctures
INSERT INTO products (id, sku, name, category, brand, potency, form, pack_size, uom, cost_price, selling_price, mrp, tax_percent, hsn_code, manufacturer, description, barcode, reorder_level, min_stock, max_stock, current_stock, is_active, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'SBL-ARN-Q-30ML', 'Arnica Montana Q', 'Mother Tinctures (Q)', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Mother Tincture', '30ml', 'ml', 90, 120, 140, 12, '30039011', 'SBL', 'External injuries, muscle pain relief', '', 25, 15, 250, 80, true, 'trauma,external,pain', now(), now()),
(gen_random_uuid(), 'SBL-CALEN-Q-30ML', 'Calendula Officinalis Q', 'Mother Tinctures (Q)', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Mother Tincture', '30ml', 'ml', 90, 120, 140, 12, '30039011', 'SBL', 'Wound healing, antiseptic properties', '', 25, 15, 250, 80, true, 'wound,healing,antiseptic', now(), now()),
(gen_random_uuid(), 'SBL-ECHIN-Q-30ML', 'Echinacea Angustifolia Q', 'Mother Tinctures (Q)', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Mother Tincture', '30ml', 'ml', 110, 140, 165, 12, '30039011', 'SBL', 'Immunity booster, infections', '', 20, 10, 200, 60, true, 'immunity,infection,boost', now(), now()),
(gen_random_uuid(), 'SBL-BERB-Q-30ML', 'Berberis Vulgaris Q', 'Mother Tinctures (Q)', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Mother Tincture', '30ml', 'ml', 95, 125, 145, 12, '30039011', 'SBL', 'Kidney stones, urinary problems', '', 15, 10, 150, 50, true, 'kidney,urinary,stones', now(), now()),
(gen_random_uuid(), 'SBL-THUJA-Q-30ML', 'Thuja Occidentalis Q', 'Mother Tinctures (Q)', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Mother Tincture', '30ml', 'ml', 95, 125, 145, 12, '30039011', 'SBL', 'Warts, skin growths, vaccination effects', '', 15, 10, 150, 50, true, 'warts,skin,vaccination', now(), now());

-- Top 5 Biochemic Tablets (6X potency)
INSERT INTO products (id, sku, name, category, brand, potency, form, pack_size, uom, cost_price, selling_price, mrp, tax_percent, hsn_code, manufacturer, description, barcode, reorder_level, min_stock, max_stock, current_stock, is_active, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'SBL-CALCPHOS-6X-25G', 'Calcarea Phosphorica 6X', 'Biochemic Tablets', 'SBL (Dr. Willmar Schwabe)', '6X', 'Tablet', '25g', 'g', 55, 70, 85, 12, '30049012', 'SBL', 'Bone development, teething, growth', '', 30, 20, 300, 100, true, 'bone,teeth,growth,children', now(), now()),
(gen_random_uuid(), 'SBL-CALCFLUOR-6X-25G', 'Calcarea Fluorica 6X', 'Biochemic Tablets', 'SBL (Dr. Willmar Schwabe)', '6X', 'Tablet', '25g', 'g', 55, 70, 85, 12, '30049012', 'SBL', 'Teeth, bones, elastic tissue', '', 25, 15, 250, 90, true, 'teeth,bone,elasticity', now(), now()),
(gen_random_uuid(), 'SBL-FERUMPHOS-6X-25G', 'Ferrum Phosphoricum 6X', 'Biochemic Tablets', 'SBL (Dr. Willmar Schwabe)', '6X', 'Tablet', '25g', 'g', 55, 70, 85, 12, '30049012', 'SBL', 'Fever, inflammation, anemia', '', 30, 20, 300, 100, true, 'fever,anemia,inflammation', now(), now()),
(gen_random_uuid(), 'SBL-NATRUMMUR-6X-25G', 'Natrum Muriaticum 6X', 'Biochemic Tablets', 'SBL (Dr. Willmar Schwabe)', '6X', 'Tablet', '25g', 'g', 55, 70, 85, 12, '30049012', 'SBL', 'Water balance, grief, headaches', '', 25, 15, 250, 90, true, 'water,headache,grief', now(), now()),
(gen_random_uuid(), 'SBL-KALISULPH-6X-25G', 'Kali Sulphuricum 6X', 'Biochemic Tablets', 'SBL (Dr. Willmar Schwabe)', '6X', 'Tablet', '25g', 'g', 55, 70, 85, 12, '30049012', 'SBL', 'Skin eruptions, yellow discharges', '', 20, 15, 200, 80, true, 'skin,discharge,yellow', now(), now());

-- Top 5 Ointments
INSERT INTO products (id, sku, name, category, brand, potency, form, pack_size, uom, cost_price, selling_price, mrp, tax_percent, hsn_code, manufacturer, description, barcode, reorder_level, min_stock, max_stock, current_stock, is_active, tags, created_at, updated_at) VALUES
(gen_random_uuid(), 'SBL-CALEN-OINT-25G', 'Calendula Ointment', 'Ointments', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Ointment', '25g', 'g', 65, 85, 100, 12, '30049013', 'SBL', 'Wound healing, cuts, burns', '', 30, 20, 300, 120, true, 'wound,healing,antiseptic', now(), now()),
(gen_random_uuid(), 'SBL-ARN-OINT-25G', 'Arnica Montana Ointment', 'Ointments', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Ointment', '25g', 'g', 65, 85, 100, 12, '30049013', 'SBL', 'Sprains, bruises, muscle pain', '', 30, 20, 300, 120, true, 'pain,bruise,sprain', now(), now()),
(gen_random_uuid(), 'SBL-GRAPHIT-OINT-25G', 'Graphites Ointment', 'Ointments', 'SBL (Dr. Willmar Schwabe)', '6X', 'Ointment', '25g', 'g', 70, 90, 105, 12, '30049013', 'SBL', 'Eczema, dry skin, cracks', '', 25, 15, 250, 100, true, 'eczema,skin,dryness', now(), now()),
(gen_random_uuid(), 'SBL-HYPERIC-OINT-25G', 'Hypericum Perforatum Ointment', 'Ointments', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Ointment', '25g', 'g', 70, 90, 105, 12, '30049013', 'SBL', 'Nerve pain, injuries with pain', '', 20, 15, 200, 80, true, 'nerve,pain,injury', now(), now()),
(gen_random_uuid(), 'SBL-RHUS-OINT-25G', 'Rhus Toxicodendron Ointment', 'Ointments', 'SBL (Dr. Willmar Schwabe)', 'Q (Mother Tincture)', 'Ointment', '25g', 'g', 70, 90, 105, 12, '30049013', 'SBL', 'Joint pain, arthritis relief', '', 20, 15, 200, 80, true, 'joint,arthritis,pain', now(), now());
