package database

// GetExpectedSchema returns all expected tables grouped by module
func GetExpectedSchema() map[string][]string {
	return map[string][]string{
		"Sales": {
			"sales_invoices",
			"sales_invoice_items",
			"sales_orders",
			"sales_order_items",
			"sales_returns",
			"sales_return_items",
			"sales_estimates",
			"sales_payments",
			"salesman_commissions",
			"hold_bills",
			"e_invoices",
		},
		"Inventory": {
			"products",
			"product_categories",
			"product_brands",
			"inventory_batches",
			"inventory_adjustments",
			"inventory_transfers",
			"inventory_damage_reports",
			"low_stock_alerts",
			"expiry_alerts",
			"stock_valuation",
		},
		"Purchases": {
			"purchase_orders",
			"purchase_order_items",
			"purchase_receipts",
			"purchase_receipt_items",
			"purchase_invoices",
			"purchase_invoice_items",
			"purchase_returns",
			"supplier_payments",
			"purchase_upload_logs",
		},
		"CRM": {
			"customers",
			"customer_groups",
			"customer_loyalty_cards",
			"customer_feedback",
			"communication_log",
			"appointments",
			"crm_campaigns",
			"crm_whatsapp_messages",
		},
		"Vendors": {
			"vendors",
			"vendor_contacts",
			"vendor_contracts",
			"vendor_credit_ledger",
			"vendor_performance",
		},
		"Finance": {
			"finance_ledgers",
			"finance_transactions",
			"finance_expenses",
			"finance_payments",
			"finance_gst_reports",
			"trial_balance",
			"bank_reconciliation",
			"vouchers",
		},
		"HR": {
			"employees",
			"attendance",
			"payrolls",
			"roles",
			"permissions",
			"user_sessions",
			"leave_requests",
		},
		"Prescriptions": {
			"prescriptions",
			"prescription_items",
			"prescription_templates",
			"patients",
		},
		"AI": {
			"ai_tasks",
			"ai_recommendations",
			"ai_learning_logs",
			"ai_enrichment_queue",
			"parsed_invoices",
			"enrichment_results",
		},
		"System": {
			"system_audit_logs",
			"system_health_status",
			"system_bug_reports",
			"system_configurations",
			"menu_items",
			"notifications",
		},
	}
}
