/**
 * Barcode Template Configurations
 * Different templates for different bottle sizes
 */

export interface BarcodeTemplate {
  id: string;
  name: string;
  width: number; // in mm
  height: number; // in mm
  description: string;
  suitableFor: string;
  layout: {
    showProductName: boolean;
    showProductCode: boolean;
    showBatchNo: boolean;
    showMRP: boolean;
    showSalePrice: boolean;
    showBarcode: boolean;
    showQRCode: boolean;
    showBrand: boolean;
    showSize: boolean;
    fontSize: 'small' | 'medium' | 'large';
  };
}

export const BARCODE_TEMPLATES: BarcodeTemplate[] = [
  {
    id: 'BarcodeT1',
    name: 'Barcode T1 - Tiny',
    width: 40,
    height: 20,
    description: 'Minimal layout for very small bottles',
    suitableFor: '5ml, 10ml bottles',
    layout: {
      showProductName: true,
      showProductCode: false,
      showBatchNo: false,
      showMRP: true,
      showSalePrice: false,
      showBarcode: true,
      showQRCode: false,
      showBrand: false,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT2',
    name: 'Barcode T2 - Extra Small',
    width: 50,
    height: 25,
    description: 'Compact layout for small bottles',
    suitableFor: '10ml, 15ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: false,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: false,
      showBrand: false,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT3',
    name: 'Barcode T3 - Small',
    width: 60,
    height: 30,
    description: 'Small layout with essential info',
    suitableFor: '20ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: false,
      showBrand: true,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT4',
    name: 'Barcode T4 - Small Plus',
    width: 65,
    height: 32,
    description: 'Small layout with QR code',
    suitableFor: '20ml, 25ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT5',
    name: 'Barcode T5 - Medium Compact',
    width: 70,
    height: 35,
    description: 'Medium compact layout',
    suitableFor: '30ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: false,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT6',
    name: 'Barcode T6 - Medium',
    width: 75,
    height: 35,
    description: 'Standard medium layout',
    suitableFor: '30ml, 50ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT7',
    name: 'Barcode T7 - Medium Plus',
    width: 80,
    height: 40,
    description: 'Medium layout with all details',
    suitableFor: '50ml, 60ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT8',
    name: 'Barcode T8 - Standard',
    width: 75,
    height: 35,
    description: 'Most common standard layout',
    suitableFor: '30ml, 50ml, 100ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT9',
    name: 'Barcode T9 - Large Compact',
    width: 85,
    height: 45,
    description: 'Large compact layout',
    suitableFor: '100ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT10',
    name: 'Barcode T10 - Large',
    width: 90,
    height: 50,
    description: 'Large layout with big fonts',
    suitableFor: '100ml, 200ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'large',
    },
  },
  {
    id: 'BarcodeT11',
    name: 'Barcode T11 - Extra Large',
    width: 100,
    height: 55,
    description: 'Extra large layout',
    suitableFor: '200ml, 500ml bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'large',
    },
  },
  {
    id: 'BarcodeT12',
    name: 'Barcode T12 - Box Label',
    width: 100,
    height: 60,
    description: 'Large layout for outer boxes',
    suitableFor: 'Outer boxes, cartons',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'large',
    },
  },
  {
    id: 'BarcodeT13',
    name: 'Barcode T13 - Tablet Strip',
    width: 70,
    height: 25,
    description: 'Horizontal layout for tablet strips',
    suitableFor: 'Tablet strips, sachets',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: false,
      showBarcode: true,
      showQRCode: false,
      showBrand: true,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT14',
    name: 'Barcode T14 - Cream/Ointment',
    width: 65,
    height: 35,
    description: 'Layout for cream tubes',
    suitableFor: 'Cream tubes, ointments',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT15',
    name: 'Barcode T15 - Mother Tincture',
    width: 80,
    height: 45,
    description: 'Layout for MT bottles',
    suitableFor: 'Mother Tincture bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT16',
    name: 'Barcode T16 - Bio Combination',
    width: 60,
    height: 30,
    description: 'Layout for bio combination tablets',
    suitableFor: 'Bio combination bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: false,
      showBrand: true,
      showSize: false,
      fontSize: 'small',
    },
  },
  {
    id: 'BarcodeT17',
    name: 'Barcode T17 - Patent Medicine',
    width: 75,
    height: 40,
    description: 'Layout for patent medicines',
    suitableFor: 'Patent medicine bottles',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeT18',
    name: 'Barcode T18 - Custom Large',
    width: 110,
    height: 65,
    description: 'Maximum size custom layout',
    suitableFor: 'Large bottles, special products',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'large',
    },
  },
  {
    id: 'BarcodeCustomise1',
    name: 'Custom Template 1',
    width: 75,
    height: 35,
    description: 'Customizable template 1',
    suitableFor: 'Custom requirements',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
  {
    id: 'BarcodeCustomise2',
    name: 'Custom Template 2',
    width: 75,
    height: 35,
    description: 'Customizable template 2',
    suitableFor: 'Custom requirements',
    layout: {
      showProductName: true,
      showProductCode: true,
      showBatchNo: true,
      showMRP: true,
      showSalePrice: true,
      showBarcode: true,
      showQRCode: true,
      showBrand: true,
      showSize: true,
      fontSize: 'medium',
    },
  },
];

export function getBarcodeTemplate(templateId: string): BarcodeTemplate | undefined {
  return BARCODE_TEMPLATES.find(t => t.id === templateId);
}

export function getDefaultTemplate(): BarcodeTemplate {
  return BARCODE_TEMPLATES.find(t => t.id === 'BarcodeT8')!;
}
