// Complete Menu Structure - 100+ Pages
export const MENU_STRUCTURE = {
  // TOP MEGA MENU
  topMenu: [
    {
      id: 'dashboard',
      title: 'Dashboard',
      icon: '📊',
      path: '/dashboard',
      hasSubmenu: false,
    },
    {
      id: 'products',
      title: 'Products',
      icon: '📦',
      path: '/products',
      hasSubmenu: true,
      submenu: [
        { title: 'Product List', path: '/products', desc: 'View all products' },
        { title: 'Add Product', path: '/products/add', desc: 'Create new product' },
        { title: 'Categories', path: '/products/categories', desc: 'Manage categories' },
        { title: 'Brands', path: '/products/brands', desc: 'Manage brands' },
        { title: 'Batches', path: '/products/batches', desc: 'Batch management' },
        { title: 'Barcodes', path: '/products/barcodes', desc: 'Generate barcodes' },
        { title: 'Price Management', path: '/products/pricing', desc: 'Manage prices' },
        { title: 'Tax Settings', path: '/products/tax', desc: 'GST configuration' },
        { title: 'Variants', path: '/products/variants', desc: 'Size, potency' },
        { title: 'Import/Export', path: '/products/import-export', desc: 'Bulk operations' },
      ],
    },
    {
      id: 'inventory',
      title: 'Inventory',
      icon: '📦',
      path: '/inventory',
      hasSubmenu: true,
      submenu: [
        { title: 'Inventory Dashboard', path: '/inventory', desc: 'Overview' },
        { title: 'Stock List', path: '/inventory/stock', desc: 'All stock' },
        { title: 'Batch Tracking', path: '/inventory/batches', desc: 'Track batches' },
        { title: 'Stock Adjustments', path: '/inventory/adjustments', desc: 'Adjust stock' },
        { title: 'Stock Transfers', path: '/inventory/transfers', desc: 'Branch transfers' },
        { title: 'Reconciliation', path: '/inventory/reconciliation', desc: 'Stock audit' },
        { title: 'Low Stock Report', path: '/inventory/low-stock', desc: 'Alerts' },
        { title: 'Dead Stock', path: '/inventory/dead-stock', desc: 'Non-moving' },
        { title: 'Stock Valuation', path: '/inventory/valuation', desc: 'Real-time value' },
        { title: 'History Log', path: '/inventory/history', desc: 'All changes' },
      ],
    },
    {
      id: 'sales',
      title: 'Sales',
      icon: '💰',
      path: '/sales',
      hasSubmenu: true,
      submenu: [
        { title: 'POS', path: '/pos', desc: 'Point of Sale' },
        { title: 'B2C Sales', path: '/sales/b2c', desc: 'Retail billing' },
        { title: 'B2B Sales', path: '/sales/b2b', desc: 'Dealer sales' },
        { title: 'D2D Sales', path: '/sales/d2d', desc: 'Dealer to dealer' },
        { title: 'Sales Orders', path: '/sales/orders', desc: 'Quotations' },
        { title: 'Sales Invoices', path: '/sales/invoices', desc: 'All invoices' },
        { title: 'Credit Sales', path: '/sales/credit', desc: 'Due management' },
        { title: 'Returns', path: '/sales/returns', desc: 'Credit notes' },
        { title: 'Receipts', path: '/sales/receipts', desc: 'Payments' },
        { title: 'e-Invoice', path: '/sales/e-invoice', desc: 'Digital invoices' },
        { title: 'Sales History', path: '/sales/history', desc: 'Customer-wise' },
      ],
    },
    {
      id: 'purchases',
      title: 'Purchases',
      icon: '🛒',
      path: '/purchases',
      hasSubmenu: true,
      submenu: [
        { title: 'Purchase Orders', path: '/purchases', desc: 'PO management' },
        { title: 'GRN', path: '/purchases/grn', desc: 'Goods receipt' },
        { title: 'Purchase Bills', path: '/purchases/bills', desc: 'Invoices' },
        { title: 'Vendor Payments', path: '/purchases/payments', desc: 'Pay vendors' },
        { title: 'Returns', path: '/purchases/returns', desc: 'Purchase returns' },
        { title: 'Price Comparison', path: '/purchases/price-comparison', desc: 'Vendor-wise' },
        { title: 'Purchase History', path: '/purchases/history', desc: 'All purchases' },
        { title: 'Credit Management', path: '/purchases/credit', desc: 'Vendor credit' },
        { title: 'AI Reorder', path: '/purchases/ai-reorder', desc: 'Auto suggestions' },
      ],
    },
    {
      id: 'customers',
      title: 'Customers',
      icon: '👥',
      path: '/customers',
      hasSubmenu: true,
      submenu: [
        { title: 'Customer List', path: '/customers', desc: 'All customers' },
        { title: 'Customer Groups', path: '/customers/groups', desc: 'Retail/B2B/VIP' },
        { title: 'Contact Details', path: '/customers/contacts', desc: 'Manage contacts' },
        { title: 'Purchase History', path: '/customers/history', desc: 'Past orders' },
        { title: 'Loyalty Points', path: '/customers/loyalty', desc: 'Points program' },
        { title: 'Outstanding', path: '/customers/outstanding', desc: 'Credit limits' },
        { title: 'Feedback', path: '/customers/feedback', desc: 'Reviews' },
        { title: 'GST Details', path: '/customers/gst', desc: 'Tax info' },
        { title: 'Address Book', path: '/customers/addresses', desc: 'Addresses' },
        { title: 'Communication', path: '/customers/communication', desc: 'WhatsApp/SMS' },
      ],
    },
    {
      id: 'vendors',
      title: 'Vendors',
      icon: '🏭',
      path: '/vendors',
      hasSubmenu: true,
      submenu: [
        { title: 'Vendor List', path: '/vendors', desc: 'All vendors' },
        { title: 'Vendor Types', path: '/vendors/types', desc: 'Mfg/Distributor' },
        { title: 'Contact Details', path: '/vendors/contacts', desc: 'Manage contacts' },
        { title: 'Purchase History', path: '/vendors/history', desc: 'Past purchases' },
        { title: 'Payment Terms', path: '/vendors/payment-terms', desc: 'Terms' },
        { title: 'Credit Management', path: '/vendors/credit', desc: 'Vendor credit' },
        { title: 'Outstanding', path: '/vendors/outstanding', desc: 'Ledger' },
        { title: 'Contracts', path: '/vendors/contracts', desc: 'Agreements' },
        { title: 'Performance', path: '/vendors/performance', desc: 'Rating' },
      ],
    },
    {
      id: 'hr',
      title: 'HR & Staff',
      icon: '👔',
      path: '/hr',
      hasSubmenu: true,
      submenu: [
        { title: 'Employee List', path: '/hr/employees', desc: 'All staff' },
        { title: 'Roles & Permissions', path: '/hr/roles', desc: 'RBAC' },
        { title: 'Attendance', path: '/hr/attendance', desc: 'Check-in/out' },
        { title: 'Leave Management', path: '/hr/leaves', desc: 'Leave requests' },
        { title: 'Shift Scheduling', path: '/hr/shifts', desc: 'Shift roster' },
        { title: 'Payroll', path: '/hr/payroll', desc: 'Salary' },
        { title: 'Incentives', path: '/hr/incentives', desc: 'Commission' },
        { title: 'Performance', path: '/hr/performance', desc: 'Tracking' },
        { title: 'Activity Log', path: '/hr/activity', desc: 'Audit' },
      ],
    },
    {
      id: 'finance',
      title: 'Finance',
      icon: '💵',
      path: '/finance',
      hasSubmenu: true,
      submenu: [
        { title: 'Sales Ledger', path: '/finance/sales-ledger', desc: 'Sales accounts' },
        { title: 'Purchase Ledger', path: '/finance/purchase-ledger', desc: 'Purchase accounts' },
        { title: 'Cash Book', path: '/finance/cashbook', desc: 'Cash transactions' },
        { title: 'Bank Book', path: '/finance/bankbook', desc: 'Bank transactions' },
        { title: 'Expenses', path: '/finance/expenses', desc: 'Expense management' },
        { title: 'Petty Cash', path: '/finance/petty-cash', desc: 'Small cash' },
        { title: 'GST Reports', path: '/finance/gst', desc: 'Tax reports' },
        { title: 'P&L', path: '/finance/pl', desc: 'Profit & Loss' },
        { title: 'Balance Sheet', path: '/finance/balance-sheet', desc: 'Balance sheet' },
        { title: 'Trial Balance', path: '/finance/trial-balance', desc: 'Trial balance' },
        { title: 'Payment Vouchers', path: '/finance/payment-vouchers', desc: 'Payments' },
        { title: 'Receipt Vouchers', path: '/finance/receipt-vouchers', desc: 'Receipts' },
        { title: 'Bank Reconciliation', path: '/finance/bank-reconciliation', desc: 'Reconcile' },
      ],
    },
    {
      id: 'reports',
      title: 'Reports',
      icon: '📊',
      path: '/reports',
      hasSubmenu: true,
      submenu: [
        { title: 'Sales Reports', path: '/reports/sales', desc: 'Sales analytics' },
        { title: 'Purchase Reports', path: '/reports/purchase', desc: 'Purchase data' },
        { title: 'Stock Reports', path: '/reports/stock', desc: 'Inventory' },
        { title: 'Batch & Expiry', path: '/reports/batch-expiry', desc: 'Expiry tracking' },
        { title: 'Profit Analysis', path: '/reports/profit', desc: 'Profit metrics' },
        { title: 'GST Reports', path: '/reports/gst', desc: 'Tax reports' },
        { title: 'Customer Reports', path: '/reports/customers', desc: 'Customer data' },
        { title: 'Vendor Reports', path: '/reports/vendors', desc: 'Vendor data' },
        { title: 'Employee Reports', path: '/reports/employees', desc: 'HR reports' },
        { title: 'Financial Statements', path: '/reports/financial', desc: 'Financials' },
        { title: 'Custom Reports', path: '/reports/custom', desc: 'Report builder' },
      ],
    },
    {
      id: 'marketing',
      title: 'Marketing',
      icon: '📢',
      path: '/marketing',
      hasSubmenu: true,
      submenu: [
        { title: 'Campaign Dashboard', path: '/marketing', desc: 'All campaigns' },
        { title: 'WhatsApp Campaign', path: '/marketing/whatsapp', desc: 'Bulk WhatsApp' },
        { title: 'SMS Campaign', path: '/marketing/sms', desc: 'SMS bulk' },
        { title: 'Email Campaign', path: '/marketing/email', desc: 'Email marketing' },
        { title: 'Offers & Coupons', path: '/marketing/offers', desc: 'Promotions' },
        { title: 'Customer Segments', path: '/marketing/segments', desc: 'Segmentation' },
        { title: 'Auto Follow-up', path: '/marketing/followup', desc: 'Auto messages' },
        { title: 'Festival Campaigns', path: '/marketing/festival', desc: 'Seasonal' },
        { title: 'Dealer Announcements', path: '/marketing/announcements', desc: 'Dealer comms' },
        { title: 'Templates', path: '/marketing/templates', desc: 'Message templates' },
      ],
    },
    {
      id: 'social',
      title: 'Social Media',
      icon: '📱',
      path: '/social',
      hasSubmenu: true,
      submenu: [
        { title: 'GMB Scheduler', path: '/social/gmb', desc: 'Google My Business' },
        { title: 'Instagram/Facebook', path: '/social/instagram', desc: 'Social posts' },
        { title: 'YouTube', path: '/social/youtube', desc: 'Video posts' },
        { title: 'WordPress', path: '/social/wordpress', desc: 'Blog auto-publish' },
        { title: 'AI Content Gen', path: '/social/ai-content', desc: 'Auto content' },
        { title: 'Hashtags/SEO', path: '/social/hashtags', desc: 'Keywords' },
        { title: 'Multi-Account', path: '/social/accounts', desc: 'Manage accounts' },
      ],
    },
    {
      id: 'crm',
      title: 'CRM',
      icon: '🎯',
      path: '/crm',
      hasSubmenu: true,
      submenu: [
        { title: 'Tickets', path: '/crm/tickets', desc: 'Complaint system' },
        { title: 'Follow-up Reminders', path: '/crm/reminders', desc: 'Auto reminders' },
        { title: 'Appointments', path: '/crm/appointments', desc: 'Booking system' },
        { title: 'Chat', path: '/crm/chat', desc: 'WhatsApp/Web' },
        { title: 'Interaction History', path: '/crm/history', desc: 'Customer interactions' },
        { title: 'Feedback', path: '/crm/feedback', desc: 'Collect feedback' },
        { title: 'AI Chatbot', path: '/crm/chatbot', desc: 'AI integration' },
      ],
    },
    {
      id: 'ai',
      title: 'AI Tools',
      icon: '🤖',
      path: '/ai',
      hasSubmenu: true,
      submenu: [
        { title: 'AI Chat', path: '/ai/chat', desc: 'Business assistant' },
        { title: 'Product Suggestions', path: '/ai/product-suggestions', desc: 'Cross-sell' },
        { title: 'Demand Forecasting', path: '/ai/forecasting', desc: 'Predict demand' },
        { title: 'PO Generator', path: '/ai/po-generator', desc: 'Auto PO' },
        { title: 'Sales Insights', path: '/ai/sales-insights', desc: 'AI analytics' },
        { title: 'Price Optimization', path: '/ai/pricing', desc: 'Dynamic pricing' },
        { title: 'Content Writer', path: '/ai/content', desc: 'Posts/Blogs' },
        { title: 'Customer Segmentation', path: '/ai/segmentation', desc: 'AI segments' },
        { title: 'Health Suggestions', path: '/ai/health', desc: 'Doctor support' },
        { title: 'Workflow Automation', path: '/ai/automation', desc: 'Auto workflows' },
      ],
    },
    {
      id: 'analytics',
      title: 'Analytics',
      icon: '📈',
      path: '/analytics',
      hasSubmenu: true,
      submenu: [
        { title: 'Business Dashboard', path: '/analytics', desc: 'BI dashboard' },
        { title: 'KPI Dashboards', path: '/analytics/kpi', desc: 'Key metrics' },
        { title: 'Sales vs Purchase', path: '/analytics/sales-purchase', desc: 'Comparison' },
        { title: 'Product Performance', path: '/analytics/products', desc: 'Product metrics' },
        { title: 'Customer LTV', path: '/analytics/ltv', desc: 'Lifetime value' },
        { title: 'Forecasting', path: '/analytics/forecasting', desc: 'AI forecasts' },
        { title: 'Branch Comparison', path: '/analytics/branches', desc: 'Branch performance' },
        { title: 'Marketing ROI', path: '/analytics/marketing-roi', desc: 'Marketing metrics' },
        { title: 'Expense vs Profit', path: '/analytics/expense-profit', desc: 'Financial graphs' },
      ],
    },
    {
      id: 'ai-campaigns',
      title: 'AI Campaigns',
      icon: '🎨',
      path: '/ai-campaigns',
      hasSubmenu: true,
      submenu: [
        { title: 'Create Campaign', path: '/ai-campaigns/create', desc: 'AI-generated' },
        { title: 'Multi-Channel', path: '/ai-campaigns/multi-channel', desc: 'Deploy everywhere' },
        { title: 'Auto Content', path: '/ai-campaigns/auto-content', desc: 'Content + Images' },
        { title: 'Scheduling', path: '/ai-campaigns/schedule', desc: 'Trigger-based' },
        { title: 'Performance', path: '/ai-campaigns/performance', desc: 'Campaign analysis' },
      ],
    },
    {
      id: 'ai-insights',
      title: 'AI Insights',
      icon: '💡',
      path: '/ai-insights',
      hasSubmenu: true,
      submenu: [
        { title: 'Daily Summary', path: '/ai-insights/daily', desc: 'Auto summary' },
        { title: 'Product Performance', path: '/ai-insights/products', desc: 'Top/Low products' },
        { title: 'Action Suggestions', path: '/ai-insights/actions', desc: 'Reorder/Discount' },
        { title: 'Cash Flow', path: '/ai-insights/cashflow', desc: 'Predictions' },
        { title: 'Profit Leaks', path: '/ai-insights/profit-leaks', desc: 'AI alerts' },
        { title: 'Customer Behavior', path: '/ai-insights/customer-behavior', desc: 'Insights' },
      ],
    },
    {
      id: 'ai-lab',
      title: 'AI Lab',
      icon: '🔬',
      path: '/ai-lab',
      hasSubmenu: true,
      submenu: [
        { title: 'Test Features', path: '/ai-lab/test', desc: 'Experiment' },
        { title: 'Prompt Playground', path: '/ai-lab/playground', desc: 'Test prompts' },
        { title: 'Model Comparisons', path: '/ai-lab/models', desc: 'Compare LLMs' },
        { title: 'Data Training', path: '/ai-lab/training', desc: 'Train models' },
        { title: 'LLM Integration', path: '/ai-lab/integration', desc: 'Test APIs' },
        { title: 'Fine-tune', path: '/ai-lab/fine-tune', desc: 'Domain models' },
      ],
    },
    {
      id: 'settings',
      title: 'Settings',
      icon: '⚙️',
      path: '/settings',
      hasSubmenu: true,
      submenu: [
        { title: 'Company Profile', path: '/settings/company', desc: 'Company info' },
        { title: 'Branch Management', path: '/settings/branches', desc: 'Stores' },
        { title: 'Roles & Permissions', path: '/settings/roles', desc: 'Access control' },
        { title: 'Tax/GST Config', path: '/settings/tax', desc: 'Tax settings' },
        { title: 'Units & Measures', path: '/settings/units', desc: 'UOM' },
        { title: 'Payment Methods', path: '/settings/payments', desc: 'Payment options' },
        { title: 'Email/WhatsApp Gateway', path: '/settings/gateway', desc: 'API settings' },
        { title: 'AI Model Selection', path: '/settings/ai-models', desc: 'Choose AI' },
        { title: 'Backup & Restore', path: '/settings/backup', desc: 'Data backup' },
        { title: 'Notifications', path: '/settings/notifications', desc: 'Alert preferences' },
        { title: 'Integrations', path: '/settings/integrations', desc: 'API keys' },
      ],
    },
  ],

  // LEFT SIDEBAR - Quick Access (Most Used)
  leftSidebar: [
    { title: 'Dashboard', path: '/dashboard', icon: '📊', badge: null },
    { title: 'POS', path: '/pos', icon: '💳', badge: 'HOT' },
    { title: 'Products', path: '/products', icon: '📦', badge: null },
    { title: 'Stock', path: '/inventory/stock', icon: '📦', badge: null },
    { title: 'Sales', path: '/sales/invoices', icon: '💰', badge: null },
    { title: 'Purchases', path: '/purchases', icon: '🛒', badge: null },
    { title: 'Customers', path: '/customers', icon: '👥', badge: null },
    { title: 'Vendors', path: '/vendors', icon: '🏭', badge: null },
    { title: 'Reports', path: '/reports', icon: '📊', badge: null },
    { title: 'AI Assistant', path: '/ai/chat', icon: '🤖', badge: 'NEW' },
  ],

  // RIGHT SIDEBAR - Quick Actions
  rightSidebar: {
    quickActions: [
      { title: 'New Sale', path: '/pos', icon: '💰' },
      { title: 'Add Product', path: '/products/add', icon: '📦' },
      { title: 'Purchase Order', path: '/purchases/create', icon: '🛒' },
      { title: 'Stock Transfer', path: '/inventory/transfers', icon: '🔄' },
      { title: 'Create Campaign', path: '/marketing/create', icon: '📢' },
      { title: 'AI Insights', path: '/ai-insights', icon: '💡' },
    ],
  },
};
