import React, { useState } from 'react';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, Wand2, Send } from 'lucide-react';
import { toast } from 'sonner';

export function UnifiedPostComposer() {
    const [content, setContent] = useState('');
    const [platforms, setPlatforms] = useState<string[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [isPosting, setIsPosting] = useState(false);

    const availablePlatforms = [
        { id: 'instagram', label: 'Instagram' },
        { id: 'facebook', label: 'Facebook' },
        { id: 'gmb', label: 'Google My Business' },
        { id: 'whatsapp', label: 'WhatsApp Status' },
    ];

    const handlePlatformToggle = (platformId: string) => {
        setPlatforms(prev =>
            prev.includes(platformId)
                ? prev.filter(p => p !== platformId)
                : [...prev, platformId]
        );
    };

    const handleGenerateAI = async () => {
        if (!content && !confirm("Generate content based on a generic topic?")) return;

        setIsGenerating(true);
        try {
            const prompt = content || "Write a promotional post for a homeopathy clinic focusing on immunity.";
            const res = await api.social.generateContent({ prompt, topic: "General Health" });
            if (res.data.success) {
                setContent(res.data.content);
                toast.success("Content generated by AI!");
            }
        } catch (error) {
            toast.error("Failed to generate content");
            console.error(error);
        } finally {
            setIsGenerating(false);
        }
    };

    const handlePost = async () => {
        if (!content) return toast.error("Please enter some content");
        if (platforms.length === 0) return toast.error("Please select at least one platform");

        setIsPosting(true);
        try {
            const res = await api.social.post({
                content,
                platforms,
                media_url: "" // TODO: Add media upload
            });

            if (res.data.success) {
                toast.success("Posted successfully!");
                // Show results per platform
                const results = res.data.results;
                Object.entries(results).forEach(([platform, result]) => {
                    console.log(`${platform}: ${result}`);
                });
                setContent('');
                setPlatforms([]);
            }
        } catch (error) {
            toast.error("Failed to post");
            console.error(error);
        } finally {
            setIsPosting(false);
        }
    };

    return (
        <Card className="w-full max-w-2xl mx-auto">
            <CardHeader>
                <CardTitle>Unified Social Post</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="space-y-2">
                    <label className="text-sm font-medium">Content</label>
                    <div className="relative">
                        <Textarea
                            value={content}
                            onChange={(e) => setContent(e.target.value)}
                            placeholder="What's on your mind? or ask AI to write it..."
                            className="min-h-[150px] pr-12"
                        />
                        <Button
                            size="icon"
                            variant="ghost"
                            className="absolute top-2 right-2 text-purple-600 hover:bg-purple-50"
                            onClick={handleGenerateAI}
                            disabled={isGenerating}
                            title="Generate with AI"
                        >
                            {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
                        </Button>
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium">Post to:</label>
                    <div className="flex flex-wrap gap-4">
                        {availablePlatforms.map(platform => (
                            <div key={platform.id} className="flex items-center space-x-2">
                                <Checkbox
                                    id={platform.id}
                                    checked={platforms.includes(platform.id)}
                                    onCheckedChange={() => handlePlatformToggle(platform.id)}
                                />
                                <label
                                    htmlFor={platform.id}
                                    className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                                >
                                    {platform.label}
                                </label>
                            </div>
                        ))}
                    </div>
                </div>

                <Button
                    className="w-full"
                    onClick={handlePost}
                    disabled={isPosting || !content || platforms.length === 0}
                >
                    {isPosting ? (
                        <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Posting...
                        </>
                    ) : (
                        <>
                            <Send className="mr-2 h-4 w-4" /> Post Now
                        </>
                    )}
                </Button>
            </CardContent>
        </Card>
    );
}
