
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjujwogpqahgsonwcxdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdWp3b2dwcWFoZ3NvbndjeGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTU5MTYsImV4cCI6MjA1OTU3MTkxNn0.g2I-HSC-PKJ5eGzlqqX5hXkbVGgWxu9x2X5t7tI-bac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Additionally export URL and key constants for use in initialization
export const SUPABASE_CONFIG = {
  url: SUPABASE_URL,
  key: SUPABASE_PUBLISHABLE_KEY
};
